services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=123123  
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data
    mongodb:
        image: mongo
        environment:
            -  MONGO_INITDB_ROOT_USERNAME=davitichkhaidze5
            - MONGO_INITDB_ROOT_PASSWORD=iayBACeKfUN7XmL5
        ports:
            - 27017:27017
        volumes:
            - /data/db

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    auction-svc:
        image: davidchkh5/auction-svc:latest
        build:
            context: .
            dockerfile: AuctionService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres:5432; User Id=postgres;Password=123123;Database=auction
            - IdentityServiceUrl=http://identity-svc
        ports:
        - 5001:80
        depends_on:
            - postgres
            - rabbitmq
    search-svc:
        image: davidchkh5/search-svc:latest
        build:
            context: .
            dockerfile: SearchService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDbConnection=mongodb+srv://davitichkhaidze5:iayBACeKfUN7XmL5@cluster0.delb4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
            - AuctionServiceUrl=http://auction-svc
        ports:
        - 5002:80
        depends_on:
            - mongodb
            - rabbitmq
    identity-svc:
        image: davidchkh5/identity-svc:latest
        build:
            context: .
            dockerfile: IdentityService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=postgres:5432; User Id=postgres;Password=123123;Database=identity
        ports:
        - 5000:80
        depends_on:
            - postgres
    gateway-svc:
        image: davidchkh5/gateway-svc:latest
        build:
            context: .
            dockerfile: GatewayService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
        ports:
        - 6001:80